spring.application.name=FleetManagementAPI

spring.profiles.active=local

spring.jpa.open-in-view=false

# ----------------------------------------
# JWT Defaults
# ----------------------------------------

jwt.expiration=3600000

# ----------------------------------------
# Actuator Monitoring
# ----------------------------------------

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized