spring.application.name=SpringBootApiTemplate

# Default profile for local development.
# Override using SPRING_PROFILES_ACTIVE environment variable.

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.jpa.open-in-view=false

# ----------------------------------------
# JWT Defaults
# ----------------------------------------

jwt.expiration=3600000

# ----------------------------------------
# Actuator Monitoring
# ----------------------------------------

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized