spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# ----------------------------------------
# JWT
# ----------------------------------------

jwt.secret=test-secret-key-test-secret-key-test-secret-key-test-secret-key
jwt.expiration=3600000