spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ----------------------------------------
# JWT
# ----------------------------------------

jwt.secret=${JWT_SECRET}dd
jwt.expiration=900000

# ----------------------------------------
# Logging
# ----------------------------------------

logging.level.root=INFO

# Application logs
logging.level.com.dylanclarke.FleetManagementAPI=INFO

# Spring Security
logging.level.org.springframework.security=WARN

# Hibernate
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# Web requests
logging.level.org.springframework.web=WARN