name: Build and Test

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: fleet_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4


      - name: Build and Test
        env:
          DB_PASSWORD: postgres
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean build